name: cns_haem
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anndata=0.10.2=pyhd8ed1ab_0
  - anyio=4.0.0=pyhd8ed1ab_0
  - array-api-compat=1.4=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.20.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dnspython=2.4.2=pyhd8ed1ab_1
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - filelock=3.12.4=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - future=0.18.3=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf5=1.14.2=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperopt=0.1.2=py_0
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.4.0=pyhd8ed1ab_0
  - jupyter_core=5.4.0=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libblas=3.9.0=19_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=19_linux64_openblas
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=19_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.24.3=hf27288f_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - matplotlib-base=3.8.0=py310h62c0568_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.1.3=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3=pyhd8ed1ab_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pynndescent=0.5.10=pyh1a96a4e_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.0.0=cpu_generic_py310he67e19a_3
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - scanpy=1.9.5=pyhd8ed1ab_0
  - scvi=0.6.8=py_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stdlib-list=0.8.0=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_1
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=h2797004_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.11.2=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=hfc55251_0
  - pip:
    - cffi==1.16.0
    - contourpy==1.1.1
    - cryptography==41.0.4
    - debugpy==1.8.0
    - fonttools==4.43.1
    - gmpy2==2.1.2
    - h5py==3.10.0
    - ipykernel==6.14.0
    - ipython==8.4.0
    - jupyter-core==5.4.0
    - kiwisolver==1.4.5
    - llvmlite==0.40.1
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - numba==0.57.1
    - numpy==1.24.4
    - pandas==2.1.1
    - pillow==10.1.0
    - psutil==5.9.5
    - pymongo==4.5.0
    - pyzmq==25.1.1
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - statsmodels==0.14.0
    - torch==2.0.0.post3
    - tornado==6.3.3
    - umap-learn==0.5.4
    - unicodedata2==15.1.0
prefix: /home/jovyan/my-conda-envs/cns_haem
